spring:
  profiles:
    active: development

server:
  servlet:
    context-path: /spring-boot-aide-memoire

sentry:
  dsn: http://example@sentry.localhost:12345/1
  environment: development
  debug: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  health:
    defaults:
      enabled: false
